### ISSUE TITLE
Merged overlayfs is called overlay now, needs an additional workdir

### ISSUE THREAD

**Issue by julian-klode** [codelibre-net/schroot#1]
Since overlayfs was merged it was renamed overlay, and now requires an additional workdir option. The work dir must be an empty directory located on the same file system as the upper dir. It is used for atomic file stuff.

**Comment by fsateler** [comment]
I managed to get this working by doing the following in 10mount:do_mount_fs_union:


            overlayfs)
                # mount type is overlay...
                CHROOT_UNION_TYPE=overlay
                mkdir -p ${CHROOT_UNION_OVERLAY_DIRECTORY}/upper ${CHROOT_UNION_OVERLAY_DIRECTORY}/work
                CHROOT_UNION_MOUNT_OPTIONS="lowerdir=${CHROOT_UNION_UNDERLAY_DIRECTORY},upperdir=${CHROOT_UNION_OVERLAY_DIRECTORY}/upper,workdir=${CHROOT_UNION_OVERLAY_DIRECTORY}/work"

**Comment by rleigh-codelibre** [comment]
If this is a backward-incompatible change, we probably need to add "overlay" as an alternative type to the existing options so they don't conflict.

**Comment by julian-klode** [comment]
Yes, the file system is now called overlay instead of overlayfs, so that's not an issue at all, because you can just introduce it as an additional one.

It's great the /work seems to work, I'm not sure if that's really allowed though, in case you're working on /work inside the chroot. But I have not asked the overlayfs authors, so I don't know. If it is indeed possible, something like /.work (with the extra dot in front to hide it) would probably be a good idea to use here.

**Comment by fsateler** [comment]
@julian-klode I'm not sure I follow. You cannot work on /work inside the chroot because the chroot is mounted on /upper. /work is not visible from the chroot.

**Comment by julian-klode** [comment]
Ah, OK, it's one level up. I missed that. Does that work with multiple overlay mounts using the same work directory?

**Comment by fsateler** [comment]
I don't think so. [The docs](https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt) say:

> The "workdir" needs to be an empty directory on the same filesystem as upperdir.

So, I guess the should could be bound to the session name.

**Comment by nomeata** [comment]
Has someone a patch I could try and use? My Debian work is dependent on my schroot setup in various ways, and with aufs removed from the kernel, this is quite a stopper here.

**Comment by julian-klode** [comment]
@nomeata Here's my hack for 10mount:

https://people.debian.org/~jak/10mount-overlay.diff

It makes it work, but it does not clean up the created working directories when you end the session. My /var/lib/schroot/union/overlay/ is a tmpfs, though, so that's not a huge issue for me.

**Comment by fsateler** [comment]
@julian-klode I don't think workdir is supposed to be accessible from the overlay mount. Better mkdir .work and .upper and use them:

    mkdir -p ${CHROOT_UNION_OVERLAY_DIRECTORY}/upper ${CHROOT_UNION_OVERLAY_DIRECTORY}/work
    CHROOT_UNION_MOUNT_OPTIONS="lowerdir=${CHROOT_UNION_UNDERLAY_DIRECTORY},upperdir=${CHROOT_UNION_OVERLAY_DIRECTORY}/upper,workdir=${CHROOT_UNION_OVERLAY_DIRECTORY}/work"

I just noticed that the overlay dir is already session-id-namespaced so there is no need to add session id to work and upper. I tried simultaneous sbuild and did not have a problem.

**Comment by terceiro** [comment]
It seems I got it working with a patch based on Felipe's. Both the patch and a ready-to-build source package are at https://people.debian.org/~terceiro/schroot-overlay/

**Comment by rhertzog** [comment]
@rleigh-codelibre Any plan to merge @terceiro patch? I have been using for a while and it's a pity that the current schroot does not support this since Debian Testing/Sid no longer have aufs but only overlay.

**Comment by rleigh-dundee** [comment]
@rhertzog Yes, I will apply it, I've just been busy with other things and also lacking a suitable system to test it, not having a Debian system at the moment.  However, I have an SSD arriving tomorrow which I intend to use to set up some VMs to test this and other schroot-related work.  So hopefully soon.  But please don't let my slowness prevent it being patched and uploaded in Debian ahead of a new upstream release.

**Comment by rleigh-codelibre** [comment]
@terceiro The URL for your patch is no longer valid.  Would it be posssible to open a pull request for this?

**Comment by rleigh-codelibre** [comment]
Note that the repository was migrated to GitLab, along with these issues.  Please see https://gitlab.com/codelibre/schroot/issues/1 for future activity.
