### ISSUE TITLE
getpwuid failure with long GECOS field

### ISSUE THREAD

**Issue by ghost** [codelibre-net/schroot#19]
From: Jan-Pieter Cornet

"schroot" kept failing in our environment for specific users. But as soon as the GECOS field for that user was shortened, it started working again. We did some debugging/testing, and came up with the very simple patch below. Don't know exactly why this was necessary, the code should retry the getpwuid_r (or getgrgid_r) call when it fails, but it apparently didn't (and strace also showed that the call wasn't retried). I could try decorating the call with syslog instructions to debug this further, but a simple increase in buffer size was enough in our case, and frankly the build time was a bit excessive to do a lot of experimenting (not being used to developing in C++ I simply fired up the debian cowbuilder - it takes a while...)

```
buildbox-wheezy:~/schroot-1.6.4 $ cat debian/patches/xs4all-bufsize 
--- a/sbuild/sbuild-util.cc
+++ b/sbuild/sbuild-util.cc
@@ -624,7 +624,7 @@
 void
 sbuild::passwd::query_uid (uid_t uid)
 {
-  buffer_type::size_type size = 1 << 7;
+  buffer_type::size_type size = 1 << 10;
   buffer.reserve(size);
   int error;

@@ -733,7 +733,7 @@
 void
 sbuild::group::query_gid (gid_t gid)
 {
-  buffer_type::size_type size = 1 << 7;
+  buffer_type::size_type size = 1 << 10;
   buffer.reserve(size);
   int error;
```

We could trigger the error by having a user with a very long GECOS field (about 100 characters should certainly trigger it, but shorter ones of about 40 characters already seemed to hit the limit). schroot would exit with:

```
E: User ‘1234’ not found.
```

**Comment by rleigh-codelibre** [comment]
Note that the repository was migrated to GitLab, along with these issues. Please see https://gitlab.com/codelibre/schroot/issues/10 for future activity.
