### ISSUE TITLE
main::resolve_path() in /libexec/mount/main.cc does not work as expected in some situations

### ISSUE THREAD

**Issue by yann-soubeyrand** [codelibre-net/schroot#21]
During my work on https://github.com/codelibre-net/schroot/pull/20, I had a look at the main::resolve_path() function in /libexec/mount/main.cc. I've identified cases where this function does not work as expected.

For example, on a Debian Jessie chroot, /var/run is an absolute symlink to /run. Suppose there is a /run/test1 directory inside this chroot and this directory contains a test2 directory (/run/test1/test2). Also, suppose there is /run/test1 symlink on the host which points to /run and there is a /run/test2 directory on the host. Adding an entry like this
/opt        /var/run/test1/test2    none    rw,bind         0       0
in the mount configuration file of the chroot won't mount /opt on /run/test1/test2 inside the chroot as expected but on /run/test2 inside the chroot.

I think the algorithm I've used in the aforementioned pull request could fix this issue but I had no time to translate it in C++ yet.

**Comment by tyhicks** [comment]
I believe that a patch I've previously proposed in the Debian BTS fixes this bug. See this comment for the patch against a couple different schroot versions:

  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=728096#34

**Comment by rleigh-codelibre** [comment]
Note that the repository was migrated to GitLab, along with these issues. Please see https://gitlab.com/codelibre/schroot/issues/21 for future activity.
