### ISSUE TITLE
Sessions remain because schroot needs too much time killing its processes

### ISSUE THREAD

**Issue by tirolerstefan** [codelibre-net/schroot#23]
I experienced remaining sessions and investigated on that.
In my build environment I found out that sometimes, more than 5 processes needed to be killed. Due to the 1 second delay after each SIGTERM, the overall time for killing all N processes is N seconds (best case).

The problem is that tools like QTCreator on build abort have a 5 seconds timeout before they kill the building process (here: schroot). So, sometimes schroot had no chance to clean up everything within 5 seconds.

Remaing sessions are the result.

**Comment by rleigh-codelibre** [comment]
Note that the repository was migrated to GitLab, along with these issues. Please see https://gitlab.com/codelibre/schroot/issues/23 for future activity.
